.include "dict_core.inc"
.include "words/estore.asm"
.include "words/efetch.asm"

.include "words/istore.asm"
.include "words/istore_nrww.asm"
.include "words/ifetch.asm"

.include "dict_minimum.inc"

.include "words/d-2star.asm"
.include "words/d-plus.asm"
.include "words/d-minus.asm"
.include "words/d-invert.asm"
.include "words/udot.asm"
.include "words/dot-s.asm"

.include "words/dotstring.asm"
.include "words/squote.asm"

.include "words/words.asm"

.include "words/edefer.asm"
.include "words/rdefer.asm"
.include "words/is.asm"

.include "words/applturnkey.asm"
.include "words/int-store.asm"
.include "words/1ms.asm"
.include "words/ms.asm"

.include "dict_compiler.inc"
.include "words/show-wordlist.asm"
.include "device.inc"