#!/usr/bin/perl
use strict;

my %XT;
my %VOC;
my %ASM;
my %USEDBY;
my %DESCRIPTION;
my %STACK;
my %DSTACK;
my %RSTACK;

my $htmldir="../doc/html/words";
my $asmdir="../core/words";

sub readASM {
    my ($filename) = @_;
    open(ASM, $filename) or die ("$filename: $!\n");
    my @ASM = <ASM>;
    close(ASM);
    my $ASM = "";
    my ($lbl, $state, $voc, $xt, $stack, $dstack, $rstack, $category);
    my ($prevline1, $prevline2, $prevline3, $description) = ("","","", "");
    foreach my $line (@ASM) {
	$line =~ s/_VE_HEAD/VE_HEAD/;
	$ASM .= $line;
	if($line=~/^VE_(.*):/) {
	    $ASM = "";
	    $lbl = "XT_$1";
	    $state = "new_header_found";
	    $voc   = "(unnamed)";
	    $category = "unclassified";
	    $dstack = $prevline3;
	    $dstack = "( $1 )" if $dstack=~/\((.+)\)/;
	    $rstack = $prevline2;
	    $rstack = "R( $1 )" if $rstack=~/\((.+)\)/;
            $description = "<pre>$1</pre>" if $prevline1=~/^;(.*)/;
	    if( $prevline3=~/; \((.+)\)\s+(.+)$/) {
	        $category = $2;
		$dstack   = "( $1 )";
	    }
	    $stack = "$dstack\n$rstack";
	}
	if($line=~/^;VE_(.*):/) {
	    # start a new definition
	    $ASM = "";
	    $lbl = "XT_$1";
	    $state = "new_header_found";
	    $voc   = "(hidden)";
	    $dstack = $prevline3;
	    $dstack = "( $1 )" if $dstack=~/\((.+)\)/;
	    $rstack = $prevline2;
	    $rstack = "R( $1 )" if $rstack=~/\((.+)\)/;
	    if( $prevline3=~/; \((.+)\)\s+(.+)$/) {
	        $category = $2;
		$dstack   = "( $1 )";
	    }
            $description = "<pre>$1</pre>" if $prevline1=~/^;(.*)/;
	    $category = "internal/hidden";
	    $stack = "$dstack\n$rstack";
	    next;
	}
	if($state =~ /new_header_found/ && $line=~/.db\s*(.*)/) {
	    my @voc = split/,/, $1;
	    my $i=0;
	    $voc = "";
	    foreach my $v (@voc) {
		#print "[$v]";
		next if $i++ == 0;
		$voc .= chr(hex($1)) if $v=~/\$([\da-fA-F]+)/;
		$voc .= $1 if $v=~/"(\S+)"/;
	    }
	    $state = "vocabulary entry found";
	    $STACK{$lbl} = $stack;
	    next;
	}
	if($line=~/^XT_(.*)/){
	    $state = "xt_found";
	    next;
	}
	if($state=~/xt_found/ && $line=~/.dw\s+(\w+)/) {
	    $xt = $1;
	    $state = "header_complete";
	    next;
	}
	if($state =~ /header_complete/) {
	    $DSTACK{$lbl} = $dstack;
	    $RSTACK{$lbl} = $rstack;

	    $XT{"$lbl"} = $xt;
	    $VOC{"$lbl"} = $voc;
            $DESCRIPTION{$lbl} = $description;
	    $state = "parsing_body";
	    next;
	}
        $prevline3 = $prevline2;
        $prevline2 = $prevline1;
        $prevline1 = $line;

	if($state =~ /parsing_body/) {
	    $ASM{$lbl} = $ASM if $ASM=~/\w/;
	}
    }
}

sub used_by {
    foreach my $lbl (keys %XT) {
	my $xt  = $XT{$lbl};
	my $voc = $VOC{$lbl};
	my $ASM = $ASM{$lbl};
	my $shortlbl = substr($lbl, 3);
	my @occ = ();
	if($xt=~/PFA_$shortlbl/) {
	    # print  "coded in assembly";
	} elsif($xt=~/PFA_DOVARIABLE/) {
	    # print "is a variable";
	} elsif($xt=~/PFA_DOVALUE/) {
	    # print "is a value";
	} elsif($xt=~/PFA_DODEFER/) {
	    # print "is a defer";
	} elsif($xt=~/PFA_DOUSER/) {
	    # print "   USER VARIABLE";
	} elsif($xt=~/DO_COLON/) {
	    foreach my $line (split /\n/, $ASM) {
		next unless $line=~/(\s+)\.dw\s+(\S*)\s*.*/;
		my ($curvoc, $curxt);
		next unless $line=~/\.dw XT_(\S*)/;
		my $curxt = "XT_".$1;
		$USEDBY{$curxt}{$lbl} = 1;
	    }
	} else {
	    print "  used by UNKNOWN TYPE: $xt $voc $ASM\n";
	}
    }

}

sub format_xt {
    my ($xt,  $indent) = @_;
    my $voc = $xt;
    $xt = uc $xt;
    $xt = "XT_${xt}" unless $xt=~/^XT_/;
    if( defined $VOC{$xt} ) {
	chomp($voc);
	$voc = $VOC{$xt};
	$voc =~ s/>/&gt;/g;
	$voc =~ s/</&lt;/g;
	$voc =  "&nbsp;" x $indent . " <a href=\"$xt.php\">$voc</a> ";
    }
    return $voc;
}

sub html_head {
    my ($title) = @_;
    return "<html><title>amforth: $title</title>
    <link rel=\"stylesheet\" type=\"text/css\" href=\"../amforth.css\">
</head>\n<body><?php include \"../menu.inc\"?>";
}

sub html_foot {
    return "<hr/>
 <p>Hosted by <a href=\"http://sourceforge.net\"> <IMG
                src=\"http://sourceforge.net/sflogo.php?group_id=29376\"
                width=\"88\" height=\"31\" border=\"0\" alt=\"SourceForge
                Logo\"></a></p>

<p class=notebox>
<a href=\"mailto:amforth-devel\@lists.sourceforge.net\">amforth-devel\@lists.sourceforge.net</a></p>
</body>\n</html>\n";
}



sub printHTML {
    my @PRIMITIVES = ();
    my @VARIABLES = ();
    my @VALUES    = ();
    my @USERVARS  = ();
    my @COLONS    = ();
    my @DEFERS    = ();
    
    foreach my $lbl (keys %XT) {
	my $xt  = $XT{$lbl};
	my $voc = $VOC{$lbl};
	my $ASM = $ASM{$lbl};
	my $shortlbl = substr($lbl, 3);
	#print "$lbl $voc $xt $shortlbl";
	open(HTML, ">$htmldir/$lbl.php");
	print HTML html_head($voc);
	print HTML "<h1>$voc</h1>\n";
        print HTML "<p>$DESCRIPTION{$lbl}</p>\n";
	print HTML "<h2>Stackeffects</h2>\n";
	my @s = split /\n/, $STACK{$lbl};
	$s[0] =~ s/;//g;
	$s[1] =~ s/;//g;
	print HTML "$s[0]\n<br>$s[1]";
	print HTML "<h2>Definition</h2>\n";
	if($xt=~/PFA_$shortlbl/) {
	    print HTML "coded in assembler";
	    push @PRIMITIVES, $lbl;
	} elsif($xt=~/PFA_DOVARIABLE/) {
	    print HTML "<pre>
		variable $voc
</pre>";
	    push @VARIABLES, $lbl;
	} elsif($xt=~/PFA_DOVALUE/) {
	    my $offset = 0;
	    if ($ASM=~/\.dw\s+(\d+)/) {
		$offset = $1;
	    }
	    print HTML "<pre>
		( $offset ) value $voc
</pre>";
	    push @VALUES, $lbl;
	} elsif($xt=~/PFA_DODEFER/) {
	    my $offset = 0;
	    if ($ASM=~/\.dw\s+(\d+)/) {
		$offset = $1;
	    }
	    print HTML "<pre>
		( $offset ) defer $voc
</pre>";
	    push @DEFERS, $lbl;
	} elsif($xt=~/PFA_DOUSER/) {
	    # print "   USER VARIABLE";
	    my $offset = 0;
	    if ($ASM=~/\.dw\s+(\d+)/) {
		$offset = $1;
	    }
	    print HTML "<pre>
		$offset user $voc
</pre>";
	    push @USERVARS, $lbl;
	} elsif($xt=~/DO_COLON/) {
	    my $state = "normal";
	    my $indent = 2;
	    push @COLONS, $lbl;
	    print HTML "<code>\n: $voc<br>\n";
	    my @lines = split /\n/, $ASM;
	    my $curlin = 0;
	    foreach my $line (@lines) {
		last if $curlin++ == $#lines;
		print HTML "\n<br>$line\n<br>" if $line=~/^PFA_.*\d:/;
		next unless $line=~/(\s+)\.d[wb]\s+(.*)\s*.*/;
		my $number = $2;
		my $cindent = length($1);
		my ($curvoc, $curxt);
		if($state =~/print_number/) {
		    $number = format_xt($number) if $number=~/XT_/;
		    print HTML  format_xt("doliteral") . $number;
		    $state = "normal";
		    next;
		}

		if($state =~/print_compile (.*)/) {
		    print HTML "\n<br>" .format_xt($1) . "\n<br>";
		    $state = "normal";
		    next;
		}

		if($state =~/print_string/) {
		    $number = format_xt($number) if $number=~/XT_/;
		    print HTML  format_xt("sliteral") . $number;
		    $state = "normal";
		    next;
		}
		if($state =~ /print_jump (.*)/) {
		    print HTML "\n<br>" .format_xt($1) . $number . "\n<br>";
		    $state = "normal";
		    next;
		}
		next unless $line=~/\.dw XT_(\S*)/;
		my $curxt = "XT_".$1;
		if($curxt=~/XT_DOLITERAL/) {
		    $state = "print_number";
		    next;
		}
		if($curxt=~/XT_COMPILE/) {
		    $state = "print_compile $curxt";
		}
		if($curxt=~/XT_SLITERAL/) {
		    $state = "print_string";
		    next;
		}
		if($curxt=~/XT_DO.*BRANCH/) {
		    $state = "print_jump $curxt";
		    next;
		}

		if($curxt=~/XT_DO.*LOOP/) {
		    $state = "print_jump $curxt";
		    next;
		}

		print HTML format_xt($curxt, $indent);
	    }
	    print HTML "\n<br>;\n</code>";
	} else {
	    print "     UNKNOWN TYPE: '$xt' $voc $ASM\n";
	}
	print HTML "<h2>Used by</h2>\n";
	foreach my $xt (sort keys %{$USEDBY{$lbl}} ) {
	    print $xt;
	    print HTML format_xt($xt);
	}
	print HTML html_foot;
	close(HTML);
	# print "\n";
    }

    open(INDEX, ">$htmldir/index.php");
    print INDEX html_head("Words");

    print INDEX "<h1>Colon words</h1>";
    open(HTML, ">$htmldir/colons.php");
    print HTML html_head("Colon Words");
    foreach my $variable (sort @COLONS) {
	print HTML format_xt($variable)."\n";
	print INDEX format_xt($variable) ."\n";
    }
    print HTML html_foot;
    close(HTML);

    print INDEX "<h1>Variables or Constants</h1>";
    open(HTML, ">$htmldir/variables.php");
    print HTML html_head("Variables");
    foreach my $variable (sort @VARIABLES) {
	print HTML format_xt($variable)."\n";
	print INDEX format_xt($variable)."\n";
    }

    print INDEX "<h1>Values</h1>";
    open(HTML, ">$htmldir/values.php");
    print HTML html_head("Values");
    foreach my $value (sort @VALUES) {
	print HTML format_xt($value)."\n";
	print INDEX format_xt($value)."\n";
    }

    print HTML html_foot;
    close(HTML);

    print INDEX "<h1>User Variables</h1>";
    open(HTML, ">$htmldir/uservariables.php");
    print HTML html_head("User Variables");
    foreach my $variable (sort @USERVARS) {
	print HTML format_xt($variable)."\n";
	print INDEX format_xt($variable)."\n";
    }
    print HTML html_foot;
    close(HTML);

    print INDEX "<h1>Defered Words</h1>";
    open(HTML, ">$htmldir/defer.php");
    print HTML html_head("Defered Words");
    foreach my $variable (sort @DEFERS) {
	print HTML format_xt($variable)."\n";
	print INDEX format_xt($variable) ."\n";
    }
    print HTML html_foot;
    close(HTML);

    print INDEX "<h1>Primitivs</h1>";
    open(HTML, ">$htmldir/primitives.php");
    print HTML html_head("Primitives");
    foreach my $variable (sort @PRIMITIVES) {
	print HTML format_xt($variable)."\n";
	print INDEX format_xt($variable)."\n";
    }
    print HTML html_foot;
    close(HTML);

    print INDEX html_foot;
    close(INDEX);
}

opendir(CWD, $asmdir);
foreach (reverse sort readdir(CWD)) {
        next unless -f "$asmdir/$_";
        next unless /(.*).asm$/;
        my $basename = "$asmdir/$_";
        readASM($basename);
}
print "\n";
used_by();
printHTML();
print "\n";
